import type { Metadata } from "next";
import {Plaster, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(frontend)/components/Navbar/Navbar";
import { ThemeProvider } from "./(frontend)/components/Theme/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "./(frontend)/components/App-sidebar/app-sidebar";
import LayoutWrapper from "./(frontend)/components/LayoutWrapper/LayoutWrapper";
import { Analytics } from '@vercel/analytics/next';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const PlasterFont = Plaster({
  variable: "--font-Plaster",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <SidebarProvider>
          <LayoutWrapper navbar={<Navbar/>} sidebar={<AppSidebar />}>
            {children}
            <Analytics/>
          </LayoutWrapper>
        </SidebarProvider>
           </ThemeProvider>
      </body>
    </html>
  );
}



// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
// import { AppSidebar } from "@/components/app-sidebar"

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <SidebarProvider>
//       <AppSidebar />
//       <main>
//         <SidebarTrigger />
//         {children}
//       </main>
//     </SidebarProvider>
//   )
// }